### PR TITLE
External documentation config fix

### PR DESCRIPTION
**Pull request by povilasb**
Updates code not to use default external doc links if it is set in confing for specific packages

### CODE REVIEW

**Comment by c2nes** [comment]
@povilasb Would you give us permission to relicense this contribution under the terms of the [Apache 2.0](http://opensource.org/licenses/Apache-2.0) license? We're trying to get Javasphinx on Apache 2.0 for consistency with Bronto's other open source projects.

**Comment by povilasb** [comment]
@c2nes I did not know that contributions are licensed at all :D Anyways, please interpret all my contributions MIT licensed, meaning you can do whatever you want with it :)

**Comment by c2nes** [comment]
@povilasb Thanks for the quick reply! We would ideally like to change the entire project's license to Apache 2.0 from MIT. Would Apache 2.0 be okay with you for this contribution?

**Comment by povilasb** [comment]
@c2nes yes, of course :)

**Comment by c2nes** [comment]
Thanks!

**Pull request merged**
